### ISSUE TITLE
Upgrade to Zephyr 3.2

### ISSUE THREAD

**Issue by osman** [petejohanson/technikable-zmk-config#2]
Tried following the instructions on the [announcement post](https://zmk.dev/blog/2023/04/06/zephyr-3-2), but I wasn't sure how to configure the `pinctrl` files. Any chance you could update this repo, so I can pull from upstream?

**Comment by petejohanson** [comment]
This board doesn't make use of any peripheral buses that need pinctrl changes. Should work fine as is, see this manually triggered build just now: https://github.com/petejohanson/technikable-zmk-config/actions/runs/4635639649/jobs/8202864272

Are you have any specific issues/problems?

**Comment by osman** [comment]
I see, so no updates are necessary to pick up the changes, just a rebuild?

**Comment by petejohanson** [comment]
Exactly right

**Comment by osman** [comment]
awesome! thanks for clarifying
